### ISSUE TITLE
KeenKraken new checkpoint format

### ISSUE THREAD

**Issue by branylagaffe** [parsa-epfl/flexus#39]
**I want** to change the checkpoint format for a JSON based structure
**So that** ParaFlex, KeenKraken, KnottyKraken all have the same interface

**Specification:**
1. See .json table

**Tasks:**
- [x] Specify the output format
- [x] Rewrote MMU import/export
- [x] Rewrote L1 import/export
- [x] Rewrote L2 import/export
- [x] Rewrote BP import/export

---

**UPDATE**
-[datetime]:  [description]

**Comment by branylagaffe** [comment]
He @giorgioajmone, I have bumped [QFlex](https://github.com/parsa-epfl/qflex/tree/bryan/rework) (also therefore QEMU and libqflex) to support a new command `flexus-save-ckpt` that will dump KeenKraken State into a folder

**Comment by branylagaffe** [comment]
**Update**

[15.05.2024] Export is similiar

**Comment by branylagaffe** [comment]
*Update*


@giorgioajmone added a feature to create and save the new checkpoint to a specific dir.
@giorgioajmone Is waiting on the command

**Comment by branylagaffe** [comment]
*Update*

Import still need testing

**Comment by branylagaffe** [comment]
https://github.com/parsa-epfl/flexus/tree/feat/ckpt-patch 

Contains the commits from @giorgioajmone on feat/ckpt, and some patches.
However, this lack the implementation for the loading in KnottyKraken (Cache, CacheCMP, BranchPredictor, etc).

**Comment by branylagaffe** [comment]
Commit c58536ce77dc3c517c984c046297572342cdf201 adds saving capability for TAGE
